update methods for linear
chython/chython pull request #36
Opened 2023-09-20 05:10 UTC by TimurGimadiev

2023-09-20 06:16 UTC, stsouko requested changes

2023-09-20 06:16 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> +        out = defaultdict(list)
for k, v in linear_hash_smiles().items():
    out[v].append(k)
return dict(out)

2023-09-20 06:16 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> +                            number_bit_pairs: int = 4) -> Dict[str, int]:
looks like useless with number_bit_pairs > 1

2023-09-20 06:16 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> -                                                                                                List[Tuple[int, ...]]]:
redundant

2023-09-20 06:16 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> +               fingerprint (if number of fragment in molecule greater or equal this number, we will
keep 120 symbol line border

2023-09-20 06:21 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/linear.py
> +                    for cnt in range(min(len(count), number_bit_pairs))}
my bad, in else statement should be no min function and number_bit_pairs var

2023-09-20 06:28 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/linear.py
> +               fingerprint (if number of fragment in molecule greater or equal this number, we will
be is extra word here, we will activate or it will be activated

2023-09-20 06:31 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/linear.py
> +                            number_bit_pairs: int = 4) -> Dict[str, int]:
it is useful for understanding what's going on in the fingerprints, so if you set 1 in hashes, the number of hashes in linear_smiles_hashes will not match to linear_smiles_count without this restriction

2023-09-21 20:54 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> +            for x, y in zip(chains, chains[1:]):
Chains is the list of atoms chains , not a single chain

2023-09-22 04:21 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/linear.py
> +            for x, y in zip(chains, chains[1:]):
understood

2023-09-22 12:01 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> -
keep NL

2023-09-22 12:01 UTC, stsouko commented on chython/algorithms/fingerprints/linear.py
> -
keep NL

2023-09-22 12:04 UTC, merged