update morgan with smiles methods
chython/chython pull request #38
Opened 2023-09-23 17:50 UTC by TimurGimadiev

2023-09-24 11:50 UTC, stsouko requested changes

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +from collections import defaultdict
keep original imports style

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +from numpy import uint8, zeros
2 blank lines after imports!

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +    def morgan_smiles_hash(self: "MoleculeContainer", min_radius: int = 1,
single quotes

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +                           max_radius: int = 4) -> defaultdict[Any, list[int]]:
Any or str?

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +    def morgan_smiles_hash(self: "MoleculeContainer", min_radius: int = 1,
line limit is 120 char

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +        Transform structures into integer hashes of atoms with EC.
info about output data structure

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +                           max_radius: int = 4) -> defaultdict[Any, list[int]]:
replace defaultdict by dict

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +        return smiles_dict
dd > dict

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +        for radius, hash_dict in enumerate(self._morgan_hash_dict(min_radius, max_radius)):
works correctly only with default min_radius

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +                smiles_dict[format(self.augmented_substructure((atom,), deep=radius), "A")].append(morgan_hash)
single quote

2023-09-24 11:50 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +    def morgan_smiles_bit(self, min_radius: int = 1, max_radius: int = 4, length: int = 1024,
how this can be used?

2023-09-24 14:55 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/morgan.py
> +    def morgan_smiles_bit(self, min_radius: int = 1, max_radius: int = 4, length: int = 1024,
check which bits in fingerprint correspond to this group, its interpretation of hashed fingerprint

2023-09-24 15:25 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/morgan.py
> +        return smiles_dict
haven't got this, what do you mean by it?

2023-09-24 17:14 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +        return dict(smiles_dict)
looks like it is 1-1 correspondence.

2023-09-24 17:14 UTC, stsouko commented on chython/algorithms/fingerprints/morgan.py
> +        return {smi: len(hashes) for smi, hashes in self.morgan_smiles_hash(min_radius, max_radius).items()}
looks like it is 1-1 correspondence.

2023-09-25 03:34 UTC, TimurGimadiev commented on chython/algorithms/fingerprints/morgan.py
> +        return dict(smiles_dict)
correspondence is following:
 -∞,-1,0,1     ----> deep=0  because you give only identifiers of atoms
2                 ----> deep=1  because you give only identifiers of atoms, and 1 update of identifiers
and so on....
so Morgan counts 1 as not updates - only atoms
substructures count 0 as only atoms

2023-09-29 15:52 UTC, merged